"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Giuseppe Tufo"
email = "pepj2000@gmail.com"

[ui]
editor = "nvim"
default-command = "log"

[revsets]
log = '@ | ancestors(trunk()..(visible_heads() & mine()), 2) | trunk()'

[aliases]
sync = ['git', 'fetch', '--all-remotes']
evolve = ['rebase', '--skip-emptied', '-d', 'main']
c = ['git', 'push', '-r', '@']
cl = ['git', 'push', '-r', '@-']
rb = ['bookmark', 'delete']
d = ['git', 'push', '--deleted']
setmain = ["bookmark", "move", "main", "--to", "@-"]
setdev = ["bookmark", "move", "develop", "--to", "@-"]
logxl = ['log', '-r', 'all()']
l5 = ['log', '-r', 'ancestors(@, 5)']
l10 = ['log', '-r', 'ancestors(@, 10)']
cb = ['util', 'exec', '--', 'bash', '-c', """
set -euo pipefail
jj bookmark move $1 --to @- && jj git push -r @-
""", ''] 

